#!/usr/local/bin/php
<?php

function out($message)
{
    fwrite(STDOUT, $message);
}

function in($message = NULL)
{
    if($message !== NULL)
    {
        out($message);
    }
    return fgets(STDIN);
}

function outln($message)
{
    out($message . PHP_EOL);
}

function get_array_value($array, $index, $default_value = NULL)
{
    if(array_key_exists($index, $array))
    {
        return $array[$index];
    }
    else
    {
        return $default_value;
    }
}

function show_help($amigo_name)
{
    $message = "USAGE:" . PHP_EOL .
        "* Help" . PHP_EOL .
        "   php $amigo_name help" . PHP_EOL;

    foreach(glob(__DIR__.'/amigo_res/*.php') as $file)
    {
        include_once($file);
        $class = basename($file);
        $class_parts = explode('.', $class);
        $class = $class_parts[0];
        $obj =  new $class();
        $description = property_exists($obj, 'description')? $obj->description : '';
        $parameter = property_exists($obj, 'parameter')? $obj->parameter : '';
        $command = lcfirst($class);
        $message .= "* $description" . PHP_EOL;
        $message .= "   php $amigo_name $command $parameter".PHP_EOL;
    }

    outln($message);
}

if($argc == 1 || ($argc == 2 && $argv[1] == "help"))
{
    show_help($argv[0]);
}
else if($argc == 2 && $argv[1] == "?")
{
    outln(" Do you just ask `Am I Go?`");
    outln(" No, you are not, I don't know who you are. And I'm not `Go` too. I am Amigo, a simple PHP CLI program.");
    outln(" `Go` is the programmer who made me.");
    outln(" You can stalk his github on https://github.com/goFrendiAsgard" . PHP_EOL);
    show_help($argv[0]);
}
else if($argc > 1)
{
    $command = $argv[1];
    $class = ucfirst($command);
    $file_name = __DIR__.'/amigo_res/'.$class.'.php';
    if(file_exists($file_name) && is_readable($file_name))
    {
        $arguments = array_slice($argv, 2);
        // run the class
        $class = ucfirst($command);
        include_once($file_name);
        $obj =  new $class();
        $obj->run($arguments);
    }
    else
    {
        outln("Invalid command `$command`");
        show_help($argv[0]);
    }
}
else
{
    outln("This should never be shown, but in case it is, please run away, zombie apocalypse will be happened very soon");
}

